version: '2.3'
services:
  #https://www.elastic.co/guide/en/elasticsearch/reference/6.2/docker.html
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    hostname: elastic
    environment:
      - "node.name=elastic"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS+=' -Xms1g -Xmx1g '"
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - 9200
  
  # HOWTO: add the follow address http://172.18.0.1:9200 to conect into your local ES
  cerebro:
    image: yannart/cerebro
    hostname: cerebro
    ports:
      - "9000:9000"
    expose:
      - 9000
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    hostname: kibana
    links:
      - "elastic:elasticsearch"
    ports:
      - "5601:5601"
    expose:
      - 5601
