service: logfunc

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  memorySize: 128
  runtime: nodejs8.10
  role: arn:aws:iam::911846541130:role/benie-bus-event-role
  stage: dev
  region: us-west-2

functions:
  compute:
    handler: handler.run
    events:
      - stream:
          type: kinesis
          arn:  arn:aws:kinesis:us-west-2:911846541130:stream/data 
          batchSize: 1
          startingPosition: LATEST

